export enum modelName {
    USER                = 'User',
    SESION              = 'Sesion',
    PASSWORD_RESET      = 'PasswordReset',
    WEATHER             = 'Weather',
    SECTOR              = 'Sector',
    SECTOR_HUMIDITY     = 'SectorHumidity',
    SECTOR_LIGHT        = 'SectorLight',
    SECTOR_LOCATION     = 'SectorLocation',
    SECTOR_TEMPERATURE  = 'SectorTemperature',
    TEXTURE             = 'Texture',
    CROP                = 'Crop',
    MONTH               = 'Month',
    STUDY               = 'Study',
}
